<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Tasky.BuildingBlocks\Tasky.BuildingBlocks.csproj" />
    <ProjectReference Include="..\Tasky.Services.Projects.Infrastructure\Tasky.Services.Projects.Infrastructure.csproj" />
    <ProjectReference Include="..\Tasky.Services.Projects.Application\Tasky.Services.Projects.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
