name: tasky-application
services :
  postgres:
    container_name: postgres-server
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  gateways:
    container_name: tasky-application-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    build:
      context: .
      dockerfile: Gateways/Tasky.Gateways.API/Dockerfile
    ports:
      - "5100:80"
    depends_on:
      - identities

  identities:
    container_name: tasky-identities-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - JwtSettings__Secret=yBG5WrUlLIrYVT/WqbHRGsup5m+taMg8T7IEZyOupQto=
      - PORT=80
    build:
      context: .
      dockerfile: Services/Identities/Tasky.Services.Identities.API/Dockerfile
    ports:
      - "5102:80"
    depends_on:
      - postgres
  projects:
    container_name: tasky-projects-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
    build:
      context: .
      dockerfile: Services/Projects/Tasky.Services.Projects.API/Dockerfile
    ports:
      - "5103:80"
    depends_on:
      - postgres
  
volumes:
  postgres_data:
    driver: local